QRid = 'https://authserver.nju.edu.cn/authserver/qrCode/get?ts=%d'
QRimg = 'https://authserver.nju.edu.cn/authserver/qrCode/code?uuid=%s'
status = 'https://authserver.nju.edu.cn/authserver/qrCode/status?ts=%d&uuid=%s'
login = 'https://authserver.nju.edu.cn/authserver/login?service=%s'
captcha = 'https://authserver.nju.edu.cn/authserver/captcha.html'
dynamicCode = 'https://authserver.nju.edu.cn/authserver/getDynamicCode.do'
logout = 'https://authserver.nju.edu.cn/authserver/logout.do'
